# Generated by Django 5.1.7 on 2025-03-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='readCount',
            field=models.IntegerField(default=0),
        ),
    ]
