# Generated by Django 5.1.7 on 2025-03-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_readcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imageUrl',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
